- name: Configure ssl certificate
  hosts: nginx-master
  become: yes # sudo
  ignore_unreachable: yes

  tasks:

  - name: Display domain_name variable
    debug:
      msg: "Debug variable web_domain: {{ web_domain }}"

  roles:
    # - role: 2cfg.lb.fetch_ssl_certificate
    - role: 2cfg.lb.configure_ssl_certificate
    - role: 2cfg.lb.provisioning_ssl_certificate
