all:
  hosts:
     nginx-master:
        ansible_host: 127.0.0.1
     ngx1:
        ansible_host: ngx1
     ngx2:
        ansible_host: ngx2

     ngx-lb-1:
        ansible_host: ngx-lb-1
        bgpd:
          ipaddr: 192.168.51.201
          netmask: 24
        vlan30:
          ipaddr: 192.168.47.201
          netmask: 22

          

     ngx-lb-2:
        ansible_host: ngx-lb-2
