- name: Configure ssl certificate
  hosts: nginx-master
  become: yes # sudo
  ignore_unreachable: yes

  tasks:

  - name: Display domain_name variable
    debug:
      msg: "Debug variable web_domain: {{ web_domain }}"

  - name: Display server_names variables
    debug:
      msg: "Debug variable server_names: {{ server_names }}"

  roles:
    - role: 2cfg.lb.provisioning_ssl_certificate
