- name: Configure nginx vhost
  hosts: nginx-master
  become: yes # sudo
  ignore_unreachable: yes

  tasks:

  - name: Display domain_name variable
    debug:
      msg: "Debug variable web_domain: {{ web_domain }}"

  roles:
    - role: 2cfg.lb.remove_webdomain
