---
# tasks file for 2cfg.lb.configure_nginx_server

- name: Creates directory
  file:
    path: /etc/systemd/system/nginx.service.d
    state: directory

- name: Creates directory
  file:
    path: /etc/nginx/www
    state: directory

- name: Creates directory
  file:
    path: /etc/nginx/sslcert
    state: directory


- name: Remove default vhost configuration file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Configure sysctl.conf
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    mode: 0644


- name: Configure limits.conf
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    mode: 0644


- name: Create /etc/systemd/system/nginx.service.d/override.conf
  template:
    src: nginx-override.conf.j2
    dest: /etc/systemd/system/nginx.service.d/override.conf
    mode: 0644


- name: Copying dhparams
  copy:
    src: /etc/nginx/sslcert/ssl-dhparams.pem
    dest: /etc/nginx/sslcert/ssl-dhparams.pem
    mode: 0644


- name: Copying index.html
  copy:
    src: /etc/nginx/www/index.html
    dest: /etc/nginx/www/index.html
    mode: 0644


- name: Clone nginx-lua-prometheus
  ansible.builtin.git:
    repo: 'https://github.com/knyar/nginx-lua-prometheus.git'
    dest: /etc/nginx/node_exporter


- name: Create /etc/nginx/nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644


- name: systemctl daemon-reload
  ansible.builtin.systemd:
    enabled: yes
    daemon_reload: yes
    name: nginx.service


- name: Enable zabbix-agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes


- name: Create zabbix-agent config
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    mode: 0644
  notify: Restart zabbix-agent


- name: Create sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0644

- name: Reboot server
  reboot:
    reboot_timeout: 600