---
# tasks file for 2cfg.lb.configure_nginx_server

- name: Create nginx directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/nginx
    - /etc/nginx/conf.d
    - /etc/nginx/www
    - /etc/nginx/sslcert
    - /etc/nginx/sites-enabled
    - /etc/nginx/ip_vhost.d
    - /etc/systemd/system/openresty.service.d
    - /etc/iptables
    - /etc/rc.local.d
    - /var/log/nginx
    - /var/lib/nginx
    - /var/lib/nginx/proxy_cache
    - /opt/lb_scripts

- name: Copy set_irq_affinity
  copy:
    src: set_irq_affinity
    dest: /opt/lb_scripts/set_irq_affinity
    mode: 0755

- name: Configure local_start script
  template:
    src: local_start.sh.j2
    dest: /opt/lb_scripts/local_start.sh
    mode: 0755

- name: Creates @reboot cronjob
  ansible.builtin.cron:
    name: "synchronize services"
    special_time: reboot
    job: "/opt/lb_scripts/local_start.sh"

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Configure sysctl.conf
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    mode: 0644

- name: Configure ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: 0644

- name: Configure limits.conf
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    mode: 0644

- name: Configure conntrack hashsize
  template:
    src: conntrack.conf
    dest: /etc/modprobe.d/conntrack.conf
    mode: 0644

- name: Create /etc/systemd/system/openresty.service.d/override.conf
  template:
    src: nginx-override.conf.j2
    dest: /etc/systemd/system/openresty.service.d/override.conf
    mode: 0644


- name: Generate Diffie-Hellman parameters with size 2048 bits
  community.crypto.openssl_dhparam:
    path: /etc/nginx/sslcert/ssl-dhparams.pem
    size: 2048


- name: Copying index.html
  template:
    src: index.html
    dest: /etc/nginx/www/index.html
    mode: 0644

- name: Copying iptables rules
  template:
    src: rules.v4
    dest: /etc/iptables/
    mode: 0644

- name: Copying botguard module for openresty
  copy:
    src: /usr/local/openresty/nginx/ngx_botguard_module.so
    dest: /usr/local/openresty/nginx/
    mode: 0644


- name: Copying 50-botguard.conf
  template:
    src: 50-botguard.conf
    dest: /etc/nginx/conf.d/50-botguard.conf
    mode: 0644

- name: Copying antidos lua module for openresty
  copy:
    src: anti_ddos_challenge.lua
    dest: /usr/local/openresty/nginx/
    mode: 0644


- name: Copying lb default certificate
  copy:
    src: /etc/nginx/lb.crt
    dest: /etc/nginx/
    mode: 0644

- name: Copying lb default certificate key
  copy:
    src: /etc/nginx/lb.key
    dest: /etc/nginx/
    mode: 0644

- name: Clone nginx-lua-prometheus
  ansible.builtin.git:
    repo: 'https://github.com/knyar/nginx-lua-prometheus.git'
    dest: /etc/nginx/node_exporter


- name: Create /usr/local/openresty/nginx/conf/nginx.conf
  template:
    src: nginx.conf.j2
    dest: /usr/local/openresty/nginx/conf/nginx.conf
    mode: 0644


- name: Create rc.local service
  template:
    src: rc-local.service
    dest: /etc/systemd/system/rc-local.service
    mode: 0644


- name: Create /etc/rc.local
  template:
    src: rc.local
    dest: /etc/rc.local
    mode: 0755


- name: systemctl daemon-reload
  ansible.builtin.systemd:
    enabled: yes
    daemon_reload: yes
    name: rc-local.service


- name: systemctl daemon-reload
  ansible.builtin.systemd:
    enabled: no
    daemon_reload: yes
    name: openresty.service


- name: Restart openresty.service
  ansible.builtin.service:
    name: openresty
    state: restarted


- name: Enable zabbix-agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes


- name: Create zabbix-agent config
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    mode: 0644
  notify: Restart zabbix-agent


- name: Create sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0644

- name: Reboot server
  reboot:
    reboot_timeout: 600