---
# tasks file for 2cfg.provisioning_configuration
- name: Retrieve ipaddr from mysql ipaddr_table
  community.mysql.mysql_query:
    login_db: dnsmon
    login_host: 192.168.47.106
    query: SELECT ipaddr FROM ipaddr_table WHERE remote = 'off' LIMIT 1
  register: r_query

- name: Debug processing data
  debug: "{{ item.ipaddr }}"
  with_items: "{{ r_query.query_result }}" 

- name: Create rc.local.d directory
  ansible.builtin.file:
    path: /etc/rc.local.d
    state: directory

- name: Create rc.local.d script
  template:
    src: rc.local.sh.j2
    dest: "/etc/rc.local.d/{{ item.ipaddr }}.sh"
    mode: 0755
  with_items: "{{ r_query.query_result }}"

- name: Create rc.local.d script for remote servers 
  template:
    src: rc.remote.sh.j2
    dest: "/etc/nginx/rc.local.d/{{ item.ipaddr }}.sh"
    mode: 0755
  with_items: "{{ r_query.query_result }}"

- name: Sychronize rc.local.d
  synchronize:
    src: "/etc/nginx/rc.local.d"
    dest: "/etc"
    mode: pull
    dirs: yes
  delegate_to: "{{ item }}"
  loop: "{{ groups['ngx_lb'] }}"

- name: Add arptables rule
  shell: "/usr/sbin/arptables -I INPUT -d {{ item.ipaddr }} -j DROP"
  with_items: "{{ r_query.query_result }}"

# to all srv
- name: Add ip address to interface bond0
  shell: "/usr/sbin/ip addr add {{ item.ipaddr }}/32 dev {{ iface.device }}"
  with_items: "{{ r_query.query_result }}"
  ignore_errors: yes

- name: Add ip address to interface bond0 on remote servers
  shell: "ls -1 /etc/rc.local.d/* | bash"
  ignore_errors: yes
  delegate_to: "{{ item }}"
  loop: "{{ groups['ngx_lb'] }}"

- name: Create ip_vhost.d directory
  ansible.builtin.file:
    path: /etc/nginx/ip_vhost.d
    state: directory
  delegate_to: "{{ item }}"
  loop: "{{ groups['ngx_lb'] }}"

- name: Create nginx ip_vhost.conf
  template:
    src: ip_vhost.conf.j2
    dest: /etc/nginx/ip_vhost.d/{{ item.ipaddr }}.conf
    mode: 0644
  with_items: "{{ r_query.query_result }}"

- name: Check nginx config
  shell: "/usr/sbin/nginx -t"
  register: nginx_config_status
  ignore_errors: yes

- name: Check nginx test status results for errors
  set_fact:
    nginx_config_error: 1
    cacheable: yes
  when: nginx_config_status.rc is defined and nginx_config_status.rc != 0

- block:
    - include_tasks: nginx_test_failed.yml
  any_errors_fatal: true
  when: nginx_config_error == 1
 
- name: Update ipaddr local state
  community.mysql.mysql_query:
    login_db: dnsmon
    login_host: 192.168.47.106
    query: UPDATE ipaddr_table SET remote = 'on' WHERE ipaddr = '{{ item.ipaddr }}'
  with_items: "{{ r_query.query_result }}"

- name: Sychronize ip_vhost.d conf
  synchronize:
    src: "/etc/nginx/ip_vhost.d"
    dest: "/etc/nginx"
    mode: pull
    dirs: yes
  delegate_to: "{{ item }}"
  loop: "{{ groups['ngx_lb'] }}"

- name: Check nginx config
  shell: "/usr/bin/openresty -t"
  register: nginx_config_status
  delegate_to: "{{ item }}"
  loop: "{{ groups['ngx_lb'] }}"
  ignore_errors: yes
  ignore_unreachable: yes


- name: Check nginx test status results for errors
  set_fact:
    nginx_config_error: 1
    cacheable: yes
  when: item.rc is defined and item.rc != 0
  loop: "{{ nginx_config_status.results }}"

- block:
    - include_tasks: nginx_test_failed.yml
  any_errors_fatal: true
  when: nginx_config_error == 1

- name: nginx reload
  service:
    name=openresty
    state=reloaded
  delegate_to: "{{ item }}"
  loop: "{{ groups['ngx_all'] }}"
  when: nginx_config_error == 0
  ignore_unreachable: yes