---
# tasks file for 2cfg.lb.install_common_utils
- name: Install common utilites
  apt: name={{ item }} state=present
  loop: 
    - rsync
    - git
    - netsniff-ng
    - ipset
    - ipset-persistent
    - iptables-persistent
    - netfilter-persistent
    - cpufrequtils
    - quagga-bgpd
    - zabbix-agent
    - sshfs
    - whois
    - python3-psycopg2
    - python3-pip
    - wget 
    - gnupg
    - ca-certificates
    - arptables

- name: Add apt key
  apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present
  register: import_key

- name: Add Ubuntu apt repository
  apt_repository:
    repo: "deb http://openresty.org/package/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
    state: present

- debug: msg="{{ansible_distribution}}"

- name: Install OpenResty
  apt:
    name: openresty=1.19.3.2-1~focal1
    state: present
    update_cache: yes
    install_recommends: yes


- name: Hold openresty
  dpkg_selections:
    name: openresty
    selection: hold
